Install linux-headers in dockerfile
This is required to build psutil. Without this patch, I get:

psutil/_psutil_posix.c:29:29: fatal error: linux/types.h: No such file or directory

After this patch, 'docker build' completes successfully.

See also: https://github.com/giampaolo/psutil/issues/872